### ISSUE TITLE
Default port in browser environment for relative urls

### ISSUE THREAD

**Issue by DeTeam** [substack/hyperquest#44]
I have a lib for querying an API from both node and browser which uses hyperquest.
 Right now I'm updating from a very old version and having an issue related to https://github.com/substack/hyperquest/commit/1b6050b5831a9340d2f7d947dcc5e159edc1ae42 this change. It changes the default port in browser environment to 80 even for relative urls.

Currently the question is in which place to fix it.
What would you suggest, @substack? :)

**Comment by malthejorgensen** [comment]
:+1: I'm having the same problem
