### ISSUE TITLE
[question] Way to pipe request1 to request2

### ISSUE THREAD

**Issue by nmccready** [substack/hyperquest#48]
I am trying to accomplish something that may not be in scope. I want to basically stream two request where request2 depends on the response of request1.

```
process.stdin
.pipe(request1)
.pipe(request2)
```

Where request 2 needs to process request1's response to know how to make it's query. Is this possibly without having to listen to stream events?

**Comment by zacronos** [comment]
What about something like:
```
process.stdin
.pipe(request1)
.pipe([a through stream that listens to the response from req1 and writes query for req2])
.pipe(request2)
```

**Comment by nmccready** [comment]
@zacronos I tried that but I had no luck. Where request2 needs a correct argument via the through stream.

```
process.stdin
.pipe(request1)
.pipe([a through stream that listens to the response from req1 and writes query for req2])// builds arg
.pipe(request2(arg1))
```

**Comment by zacronos** [comment]
In that case, I think you will have to do some nesting.  You don't necessarily have to listen to stream events if you don't want to though, if you find the right helper lib.  From what you've described, I would do something vaguely like (coffeescript):
```coffeescript
concat = require 'concat-stream'
process.stdin
.pipe request1
.pipe concat (response1) ->
  arg = doSomethingWith(response1)
  request2(arg).pipe concat (response2) ->
    # handle response2
```
If that won't quite do it for you, take a look at some of the other helper libs recommended by @substack: https://github.com/substack/stream-handbook

**Comment by nmccready** [comment]
Nice I'll look into concat-stream.

**Comment by nmccready** [comment]
excellent this is working thanks @zacronos
