### ISSUE TITLE
protocol specified in url is not passed to underlying http/https module

### ISSUE THREAD

**Issue by regular** [substack/hyperquest#51]
This is a problem in the following scenario:

The code

    require('hyperquest')('https://foo.com/bar')

is being browserified and served from an *http* url.

Since hyperquest does not set `opts.protocol`, the underlying module `stream-http` will infer it from `navigator.location`, which results in the wrong url being fetched, namely `http://foo.com:443/bar`.

**Comment by regular** [comment]
The bug actually is in stream-http and is address by jhiesey/stream-http#14

**Comment by juliangruber** [comment]
good find!
